
# Defined in - @ line 0

abbr g 'git'
abbr gpoat 'git push origin --all'
abbr ga 'git add .'
abbr gb 'git branch'
abbr gbl 'git blame'
abbr gc 'git commit -m'
abbr gca 'git commit --amend -m'
abbr gco 'git checkout'
abbr gcp 'git cherry-pick'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git log'
abbr gm 'git merge'
abbr gp 'git push'
abbr gpf 'git push --force-with-lease'
abbr gpl 'git pull'
abbr gr 'git remote'
abbr grb 'git rebase'
abbr gst 'git status'
abbr gam 'git commit -am '
abbr gll 'git log --graph --pretty=oneline --abbrev-commit'
